env:
  global:
  - REPO_DIR=faiss
  - BUILD_COMMIT=v1.5.3
  - BUILD_DEPENDS="numpy==1.15.0"
  - TEST_DEPENDS="numpy==1.15.0"
  - PLAT=x86_64
  - UNICODE_WIDTH=32
language: python
python: 3.5
dist: trusty
services: docker
matrix:
  exclude:
  - python: 3.5
  include:
  # manylinux1 wheels
  - os: linux
    env:
    - MB_PYTHON_VERSION=2.7
  - os: linux
    env:
    - MB_PYTHON_VERSION=2.7
    - UNICODE_WIDTH=16
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.5
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.6
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.7
  # # cuda 7.5 wheels
  # - os: linux
  #   env:
  #   - MB_PYTHON_VERSION=2.7
  #   - CUDA_VERSION=7.5
  #   - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  # - os: linux
  #   env:
  #   - MB_PYTHON_VERSION=3.5
  #   - CUDA_VERSION=7.5
  #   - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  # - os: linux
  #   env:
  #   - MB_PYTHON_VERSION=3.6
  #   - CUDA_VERSION=7.5
  #   - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  # - os: linux
  #   env:
  #   - MB_PYTHON_VERSION=3.7
  #   - CUDA_VERSION=7.5
  #   - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  # cuda 8.0 wheels
  - os: linux
    env:
    - MB_PYTHON_VERSION=2.7
    - CUDA_VERSION=8.0
    - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.5
    - CUDA_VERSION=8.0
    - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.6
    - CUDA_VERSION=8.0
    - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  - os: linux
    env:
    - MB_PYTHON_VERSION=3.7
    - CUDA_VERSION=8.0
    - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  # # cuda 9.0 wheels
  # - os: linux
  #   env:
  #   - MB_PYTHON_VERSION=2.7
  #   - CUDA_VERSION=9.0
  #   - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  # - os: linux
  #   env:
  #   - MB_PYTHON_VERSION=3.5
  #   - CUDA_VERSION=9.0
  #   - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  # - os: linux
  #   env:
  #   - MB_PYTHON_VERSION=3.6
  #   - CUDA_VERSION=9.0
  #   - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  # - os: linux
  #   env:
  #   - MB_PYTHON_VERSION=3.7
  #   - CUDA_VERSION=9.0
  #   - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  # # cuda 10.0 wheels
  # - os: linux
  #   env:
  #   - MB_PYTHON_VERSION=2.7
  #   - CUDA_VERSION=10.0
  #   - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  # - os: linux
  #   env:
  #   - MB_PYTHON_VERSION=3.5
  #   - CUDA_VERSION=10.0
  #   - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  # - os: linux
  #   env:
  #   - MB_PYTHON_VERSION=3.6
  #   - CUDA_VERSION=10.0
  #   - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  # - os: linux
  #   env:
  #   - MB_PYTHON_VERSION=3.7
  #   - CUDA_VERSION=10.0
  #   - DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
  # mac wheels
  - os: osx
    language: generic
    env:
    - MB_PYTHON_VERSION=2.7
  - os: osx
    language: generic
    env:
    - MB_PYTHON_VERSION=2.7
    - MB_PYTHON_OSX_VER=10.9
  - os: osx
    language: generic
    env:
    - MB_PYTHON_VERSION=3.5
  - os: osx
    language: generic
    env:
    - MB_PYTHON_VERSION=3.6
  - os: osx
    language: generic
    env:
    - MB_PYTHON_VERSION=3.7
    - MB_PYTHON_OSX_VER=10.9
before_install:
- source multibuild/common_utils.sh
- source multibuild/travis_steps.sh
- before_install
install:
- clean_code $REPO_DIR $BUILD_COMMIT
- mv $REPO_DIR/python/swigfaiss.swig $REPO_DIR/python/swigfaiss.i
- mv $REPO_DIR/python/faiss.py $REPO_DIR/python/__init__.py
- if [ -n "$CUDA_VERSION" ]; then
    cat conf/cuda${CUDA_VERSION}.sh >> env_vars.sh;
    export BUILD_CUDA=True;
  fi
- pip install j2cli && j2 setup.py --undefined > $REPO_DIR/setup.py
- build_wheel $REPO_DIR $PLAT
script:
- install_run $PLAT
deploy:
  provider: gcs
  access_key_id: GOOGHYKQEFMW6H6UA4PSWLPQ
  secret_access_key:
    secure: hGBWKz2jAo0tCTjtOBuuq/6b+DgajpLv4yvDuvaDAl1eB+bp1jBJOqtgLFOuNtS9Yv7M4RT0xHeRl9wUUu1GRLacBhpxuzw70sBlLNhb303TB0hMTb7Y+16NwXADru+/cWxzS3sHghzts5XJ4WdWGe48WvG3KmTqgDcTZVBUuQHAMT3zbixZvTbGQGRKbjrPPv5a/Eg78ARDvXOIORHQPZkO6ABLpmRk5Bckbyyh0DJyeKH+6naxhhnrnUzPhPQR0c9mKXSz6rV2r4gf0niUCLvlYcevqVE8cd1y0j5h3Rubh54o6tMtcj/bP7X3dtFEbuxj2CqOjOduGobL8J0K/pljuKBsaZHLn7jpw598ipPWAry6VGrXyLO/122zTvLFyhq42a74/5ONrKOLoXewsmmCaq2y/UL5D3zGMYIpthHJDMzL+cXkDL3YIBmzzh0Z05KGG+eARA8ad/BYvcSPK2bOjtL8b++Zl1Z0U24Vm4L1J5eRT/9sz5iGu2XK9MxVFL0sz9hrwgxla/2DyoOSWog5BsVPtjYn5jnPsEa07r+LTzSDVLWdUQ+URJFvUq2KCVXzozlxmWtvM/r/D3DOnYEwKN2X1urY5NSnpWsLaQlBwTlKY2AieyWzAkx//mYaNehr1UTHEgmUDfr9lSH3Ts+Sv7WlcNLJqikVvSizI88=
  bucket: ailab-wheels
  skip_cleanup: true
  local-dir: ${TRAVIS_BUILD_DIR}/wheelhouse/
  on:
    repo: kyamagu/faiss-wheels
