name: Build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - cp37-cp37m
        manylinux:
          - manylinux2010
        cuda:
          - true
          - false
    container: quay.io/pypa/${{ matrix.manylinux }}_x86_64
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Set up Python
      run: echo "::add-path::/opt/python/${{ matrix.python-version }}/bin"
    - name: Install build dependency
      run: |
        sed -i 's/mirrorlist=https/mirrorlist=http/' /etc/yum.repos.d/epel.repo
        yum install -y \
            openblas-devel \
            openblas-static \
            pcre-devel
        curl -fsSLO --retry 3 http://prdownloads.sourceforge.net/swig/swig-4.0.2.tar.gz
        tar xzf swig-4.0.2.tar.gz
        cd swig-4.0.2
        ./configure
        make -j2
        make install
        cd ..
        echo ::set-env name=FAISS_LDFLAGS::-l:libfaiss.a -l:libopenblas.a -lgfortran
    - name: Install CUDA build tools
      if: matrix.cuda
      env:
        CUDA_VERSION: 9.0
        CUDA_PKG_VERSION: 9-0-9.0.176-1
        CUBLAS_PKG_VERSION: 9-0-9.0.176.4-1
        NVIDIA_GPGKEY_SUM: d1be581509378368edeec8c1eb2958702feedf3bc3d17011adbf24efacce4ab5
        NVIDIA_GPGKEY_URL: https://developer.download.nvidia.com/compute/cuda/repos/rhel6/x86_64/7fa2af80.pub
      run: |
        curl -fsSL --retry 3 $NVIDIA_GPGKEY_URL | sed '/^Version/d' > /etc/pki/rpm-gpg/RPM-GPG-KEY-NVIDIA
        echo "$NVIDIA_GPGKEY_SUM  /etc/pki/rpm-gpg/RPM-GPG-KEY-NVIDIA" | sha256sum -c -
        tee /etc/yum.repos.d/cuda.repo <<EOF
        [cuda]
        name=cuda
        baseurl=http://developer.download.nvidia.com/compute/cuda/repos/rhel6/x86_64
        enabled=1
        gpgcheck=1
        gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-NVIDIA
        EOF
        yum install -y \
            cuda-command-line-tools-${CUDA_PKG_VERSION} \
            cuda-cublas-dev-${CUBLAS_PKG_VERSION}
        ln -s /usr/local/cuda-${CUDA_VERSION} /usr/local/cuda
        echo "/usr/local/cuda/lib64" >> /etc/ld.so.conf.d/cuda.conf
        echo "/usr/local/nvidia/lib" >> /etc/ld.so.conf.d/nvidia.conf
        echo "/usr/local/nvidia/lib64" >> /etc/ld.so.conf.d/nvidia.conf
        ldconfig
        echo ::set-env name=BUILD_CUDA::1
        echo ::set-env name=FAISS_LDFLAGS::${FAISS_LDFLAGS} -lcublas_static -lcudart_static -lculibos
        echo ::set-env name=CUDA_ARCH_FLAGS::-gencode=arch=compute_35,code=compute_35 -gencode=arch=compute_52,code=compute_52 -gencode=arch=compute_60,code=compute_60 -gencode=arch=compute_70,code=compute_70
        echo ::add-path::/usr/local/cuda/bin
    - name: Build and install faiss
      if: ${{ !matrix.cuda }}
      run: |
        cd faiss
        aclocal
        autoconf
        ./configure --without-cuda
        make -j2
        make install
        cd ..
    - name: Build and install faiss (CUDA)
      if: matrix.cuda
      run: |
        cd faiss
        aclocal
        autoconf
        ./configure --with-cuda="/usr/local/cuda" --with-cuda-arch="${CUDA_ARCH_FLAGS}"
        make -j2
        make install
        cd ..
    - name: Build package
      run: |
        mv faiss/python/swigfaiss.swig faiss/python/swigfaiss.i
        mv faiss/python/faiss.py faiss/python/__init__.py
        python -m pip install -U pip
        python -m pip install wheel numpy==1.15.0 pytest
        python setup.py install
    - name: Test
      run: |
        python -m pytest tests
  build-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version:
          - 3.7
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install build dependency
      run: |
        brew install libomp swig automake
        brew reinstall llvm
        export LLVM_PREFIX=$(brew --prefix llvm)
        export LIBOMP_PREFIX=$(brew --prefix libomp)
        echo ::set-env name=CC::${LLVM_PREFIX}/bin/clang
        echo ::set-env name=CXX::${LLVM_PREFIX}/bin/clang++
        echo ::set-env name=CFLAGS::-stdlib=libc++
        echo ::set-env name=CXXFLAGS::-stdlib=libc++
        echo ::set-env name=FAISS_LDFLAGS::/usr/local/lib/libfaiss.a -L${LIBOMP_PREFIX}/lib ${LIBOMP_PREFIX}/lib/libomp.a -framework Accelerate
    - name: Build and install faiss
      run: |
        cd faiss
        aclocal
        autoconf
        ./configure --without-cuda --with-blas="-framework Accelerate"
        make -j2
        make install
        cd ..
    - name: Build package
      run: |
        mv faiss/python/swigfaiss.swig faiss/python/swigfaiss.i
        mv faiss/python/faiss.py faiss/python/__init__.py
        python -m pip install -U pip
        python -m pip install wheel numpy==1.15.0 pytest
        python setup.py install
    - name: Test
      run: |
        python -m pytest tests
